const path = require('path')
const envPath = path.resolve(process.cwd(), '.env.local')

console.log({ envPath })

require('dotenv').config({ path: envPath })

const algoliasearch = require("algoliasearch");
const algoliaClient = algoliasearch(
  process.env.ALGOLIA_APP_ID,
  process.env.ALGOLIA_ADMIN_KEY
);
const index = algoliaClient.initIndex("dev_Bookstr");

const objects = [
  {
    OwnerFullName: "Chelsea Mulvaney",
    OwnerVerified: false,
    objectID: 64,
    interopID: 64,
    Title: "Active In My Intentions",
    Author: "Scott Nguyen",
    Description:
      "Labore reprehenderit cillum ex elit do enim dolore aute id nisi labore. Adipisicing adipisicing excepteur commodo proident quis aliquip id aute deserunt do Lorem incididunt ex Lorem. Officia pariatur do do veniam proident duis qui velit qui minim adipisicing ad nulla. Lorem pariatur consequat ullamco quis. Aute consequat nulla in eiusmod dolore. Occaecat aliquip ea magna eu. In eiusmod qui elit nostrud est ipsum deserunt.",
    Genre: "Non-Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:44.000Z",
    OwnerID: "chelseamulvaney",
  },
  {
    OwnerFullName: "Jane Pierson",
    OwnerVerified: false,
    objectID: 284,
    interopID: 284,
    Title: "Baby's Day Out",
    Author: "Rachel Day",
    Description:
      "Deserunt exercitation sit sint id exercitation do proident in. Reprehenderit excepteur officia magna proident ut ad incididunt occaecat est. Duis sunt tempor culpa enim sunt.",
    Genre: "Mystery",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:47.000Z",
    OwnerID: "janereader",
  },
  {
    OwnerFullName: "Chelsea Mulvaney",
    OwnerVerified: false,
    objectID: 54,
    interopID: 54,
    Title: "Battle Of Hell",
    Author: "Mckee Briggs",
    Description:
      "Veniam veniam veniam do deserunt velit. Fugiat nulla dolore minim ullamco tempor voluptate ullamco proident. Velit esse cillum duis do consectetur veniam duis commodo amet esse eiusmod dolor excepteur.",
    Genre: "Non-Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:44.000Z",
    OwnerID: "chelseamulvaney",
  },
  {
    OwnerFullName: "Travis Olson",
    OwnerVerified: false,
    objectID: 104,
    interopID: 104,
    Title: "Bow Of Infinity",
    Author: "Beulah Prince",
    Description:
      "Nisi ullamco dolore irure nulla laborum ad ipsum nulla laborum dolore deserunt dolore. Ut laboris Lorem sit laborum. Culpa officia et commodo elit cillum. Cillum sint id do minim dolor. Nostrud labore quis irure cupidatat deserunt. Elit dolor et ipsum fugiat elit minim occaecat id ullamco nulla incididunt laboris et sint. Quis irure eiusmod dolore magna culpa sit officia anim.",
    Genre: "Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:45.000Z",
    OwnerID: "travisolson",
  },
  {
    OwnerFullName: "Jane Pierson",
    OwnerVerified: false,
    objectID: 234,
    interopID: 234,
    Title: "Boy Affair",
    Author: "Mara Fuentes",
    Description:
      "Fugiat eiusmod culpa excepteur sint. Anim fugiat tempor in esse. Pariatur velit officia consectetur minim. Voluptate cupidatat irure veniam ipsum dolor mollit consectetur. Ea officia ipsum do non qui ea laborum incididunt adipisicing.",
    Genre: "Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:47.000Z",
    OwnerID: "janereader",
  },
  {
    OwnerFullName: "Reese Witherspoon",
    OwnerVerified: true,
    objectID: 154,
    interopID: 154,
    Title: "Call of the Wild",
    Author: "Brooke Lawson",
    Description:
      "Consectetur qui sint incididunt fugiat commodo enim elit est amet nisi velit cupidatat eu magna. Culpa cupidatat elit fugiat exercitation commodo elit cillum mollit ea velit minim velit ut. Nulla sit nostrud et cillum amet eiusmod sint. Elit ipsum voluptate velit incididunt sint aute eiusmod proident. Cupidatat elit incididunt nostrud aliquip consequat nostrud non.",
    Genre: "Non-Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:46.000Z",
    OwnerID: "reesewitherspoon",
  },
  {
    OwnerFullName: "Jane Pierson",
    OwnerVerified: false,
    objectID: 314,
    interopID: 314,
    Title: "Cat Job",
    Author: "Glover Wong",
    Description:
      "Mollit nostrud ullamco irure commodo ullamco veniam dolor dolore aliquip magna consequat nisi proident nisi. Officia incididunt nisi eiusmod proident nulla exercitation nisi excepteur amet. Enim commodo excepteur in enim esse occaecat adipisicing eiusmod eu Lorem cillum cupidatat. Adipisicing incididunt nulla adipisicing ullamco et aliquip.",
    Genre: "Other",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:48.000Z",
    OwnerID: "janereader",
  },
  {
    OwnerFullName: "Miles Nelson",
    OwnerVerified: false,
    objectID: 204,
    interopID: 204,
    Title: "Chicken Stalks Me",
    Author: "Elaine Hardin",
    Description:
      "Labore aliqua consequat excepteur est eu Lorem. Minim ullamco adipisicing et dolore commodo aliquip. Dolor aliquip veniam et culpa reprehenderit. Minim cillum dolor non nostrud nostrud culpa. Mollit velit sit nisi nostrud est duis exercitation voluptate occaecat voluptate proident ut nulla. Consequat minim culpa anim tempor nostrud sit do cillum aliqua dolore do.",
    Genre: "Mystery",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:46.000Z",
    OwnerID: "milesnelson",
  },
  {
    OwnerFullName: "Chelsea Mulvaney",
    OwnerVerified: false,
    objectID: 74,
    interopID: 74,
    Title: "Disruption With A Goal",
    Author: "Susan Carter",
    Description:
      "Magna amet ex laboris aute nisi exercitation dolore culpa. Nisi commodo reprehenderit consectetur commodo dolor laborum culpa amet. Do aliqua ad ea excepteur nulla. Quis proident quis mollit amet est ullamco Lorem esse duis esse esse consequat pariatur dolor.",
    Genre: "Non-Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:44.000Z",
    OwnerID: "chelseamulvaney",
  },
  {
    OwnerFullName: "Jane Pierson",
    OwnerVerified: false,
    objectID: 264,
    interopID: 264,
    Title: "Dogs And Armies",
    Author: "Peggy Mason",
    Description:
      "Pariatur ad id commodo incididunt culpa. Enim nisi tempor nisi ullamco fugiat duis non velit velit. Dolor ullamco sunt in voluptate voluptate et sit eiusmod nostrud nisi anim consequat. Id veniam et sit ut esse aute minim nulla tempor in. Pariatur pariatur Lorem dolor et aliqua deserunt.",
    Genre: "Other",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:47.000Z",
    OwnerID: "janereader",
  },
  {
    OwnerFullName: "Jane Pierson",
    OwnerVerified: false,
    objectID: 304,
    interopID: 304,
    Title: "Earth and Mars: A Tale",
    Author: "Alvarez Hamilton",
    Description:
      "Dolore consequat amet laboris anim pariatur incididunt eu ut laborum aliquip culpa amet anim consequat. Ad proident dolor officia cillum deserunt ea anim enim exercitation amet adipisicing sit aliquip irure. Sint dolor voluptate aliquip mollit irure exercitation aliquip officia amet dolore officia et do. Anim officia enim aliquip voluptate irure consectetur ad reprehenderit occaecat laborum laboris esse sunt. Mollit commodo ea laboris nostrud fugiat. Magna voluptate consectetur do elit laborum ea anim nulla qui Lorem occaecat cupidatat nulla. Laborum ad excepteur ex laboris adipisicing enim deserunt id veniam pariatur voluptate.",
    Genre: "Mystery",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:48.000Z",
    OwnerID: "janereader",
  },
  {
    OwnerFullName: "Jane Pierson",
    OwnerVerified: false,
    objectID: 274,
    interopID: 274,
    Title: "Ending The Fog",
    Author: "Riddle Riggs",
    Description:
      "Ipsum ex nulla quis qui culpa anim irure Lorem et laboris. Deserunt minim cupidatat anim pariatur aute. Tempor ut dolore cupidatat aliqua et voluptate eu ad minim. Esse tempor non do laborum non deserunt nulla ea nostrud aliquip officia. Enim esse id laborum nisi eu sint deserunt deserunt do nulla in est dolore. Pariatur consectetur excepteur enim ad aute anim nostrud nisi nostrud. Nostrud reprehenderit commodo cupidatat in deserunt sint enim aute nisi anim deserunt.",
    Genre: "Other",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:47.000Z",
    OwnerID: "janereader",
  },
  {
    OwnerFullName: "Miles Nelson",
    OwnerVerified: false,
    objectID: 194,
    interopID: 194,
    Title: "Evil Of The Project",
    Author: "Johnson Nichols",
    Description:
      "Voluptate cupidatat amet ex aliquip eu proident deserunt sint et non ullamco. Cupidatat fugiat nostrud non qui adipisicing non exercitation et consectetur minim laborum velit. Dolore nostrud consequat reprehenderit velit. Ad ut magna irure ipsum duis esse qui. Enim non amet esse nisi sunt cillum eu consectetur minim quis amet do. Esse irure sunt ipsum reprehenderit dolore exercitation voluptate consectetur incididunt consequat commodo.",
    Genre: "Other",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:46.000Z",
    OwnerID: "milesnelson",
  },
  {
    OwnerFullName: "Reese Witherspoon",
    OwnerVerified: true,
    objectID: 164,
    interopID: 164,
    Title: "Ghost Whisperer",
    Author: "Luna Best",
    Description:
      "Eiusmod ullamco aute laboris commodo nostrud voluptate ad nostrud velit sint. Duis ipsum duis amet nisi dolor esse laborum aliqua consequat aliquip incididunt esse esse do. Amet dolore sit fugiat sit ut cillum ullamco duis elit consequat nostrud. Ipsum nostrud consectetur eu elit anim esse nostrud Lorem anim sint. Eu cillum minim sit velit ut est occaecat est ex.",
    Genre: "Other",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:46.000Z",
    OwnerID: "reesewitherspoon",
  },
  {
    OwnerFullName: "Reese Witherspoon",
    OwnerVerified: true,
    objectID: 144,
    interopID: 144,
    Title: "Going To Spells",
    Author: "Annabelle Ramsey",
    Description:
      "Aliqua occaecat ea velit cillum. Dolor anim eiusmod ut officia eu duis fugiat sunt. Fugiat ea fugiat velit commodo irure mollit nostrud ex ullamco. Reprehenderit deserunt tempor enim laborum pariatur sunt veniam amet eu sit amet voluptate ut cillum.",
    Genre: "Other",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:45.000Z",
    OwnerID: "reesewitherspoon",
  },
  {
    OwnerFullName: "Reese Witherspoon",
    OwnerVerified: true,
    objectID: 184,
    interopID: 184,
    Title: "Guardians Of Limbo",
    Author: "Gilbert Jensen",
    Description:
      "Pariatur nulla occaecat sunt cupidatat in laborum mollit proident laborum id est proident veniam reprehenderit. Ullamco duis velit amet non proident. Pariatur exercitation magna ut esse. Mollit ullamco laboris voluptate adipisicing tempor voluptate mollit ullamco commodo et adipisicing.",
    Genre: "Non-Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:46.000Z",
    OwnerID: "reesewitherspoon",
  },
  {
    OwnerFullName: "Jane Pierson",
    OwnerVerified: false,
    objectID: 324,
    interopID: 324,
    Title: "Hiding The Skies",
    Author: "Luisa Harvey",
    Description:
      "In et nisi laborum sunt amet ipsum Lorem ipsum esse velit adipisicing. Sunt magna culpa sunt deserunt est. Velit consequat officia elit ex ipsum. Dolor commodo veniam enim fugiat id aliquip. Esse duis tempor nostrud nulla commodo adipisicing occaecat duis mollit nisi fugiat dolore elit. Ex incididunt commodo duis est ut ex ea cillum consectetur excepteur eu sit laboris adipisicing. Cillum dolore consectetur ipsum mollit ipsum magna.",
    Genre: "Other",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:48.000Z",
    OwnerID: "janereader",
  },
  {
    OwnerFullName: "Travis Olson",
    OwnerVerified: false,
    objectID: 4,
    interopID: 4,
    Title: "Intelligence Of My Journey",
    Author: "Chen Horton",
    Description:
      "Fugiat sit occaecat laboris officia nulla. Quis cillum ad exercitation sunt et. Tempor ut irure dolore amet consequat ex. Adipisicing in excepteur duis nisi qui aliquip occaecat consequat enim deserunt commodo et. Dolor consequat aute ad ullamco culpa. Lorem id tempor consectetur eu aliquip.",
    Genre: "Mystery",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:43.000Z",
    OwnerID: "travisolson",
  },
  {
    OwnerFullName: "Jane Pierson",
    OwnerVerified: false,
    objectID: 244,
    interopID: 244,
    Title: "Intelligence Of My Sister",
    Author: "Lowery Craig",
    Description:
      "Ad Lorem id Lorem minim mollit aute deserunt anim laboris ullamco qui. Nulla sunt nisi nostrud voluptate. Cupidatat nisi mollit magna magna id. Non pariatur irure laboris adipisicing cillum Lorem excepteur deserunt esse ex deserunt. Officia non id laborum excepteur aliqua reprehenderit deserunt voluptate consectetur nulla eu adipisicing proident elit.",
    Genre: "Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:47.000Z",
    OwnerID: "janereader",
  },
  {
    OwnerFullName: "Travis Olson",
    OwnerVerified: false,
    objectID: 14,
    interopID: 14,
    Title: "Jealous Of The Teacher",
    Author: "Tamara Bradford",
    Description:
      "Esse qui esse ullamco sint esse commodo do. Dolore dolor in ipsum aliquip non reprehenderit mollit aliqua adipisicing cillum. Dolor ad sit et amet amet cillum. Irure mollit anim dolor exercitation excepteur magna dolore ut proident commodo adipisicing sit.",
    Genre: "Non-Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:43.000Z",
    OwnerID: "travisolson",
  },
  {
    OwnerFullName: "Reese Witherspoon",
    OwnerVerified: true,
    objectID: 174,
    interopID: 174,
    Title: "Journey South",
    Author: "Mann Dickson",
    Description:
      "Do id culpa culpa aliquip sunt commodo est cupidatat ex aliqua labore quis. Laborum ea magna sit adipisicing incididunt magna dolore dolor. Sit ullamco nulla duis ad exercitation irure cillum velit voluptate fugiat proident ex et nisi.",
    Genre: "Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:46.000Z",
    OwnerID: "reesewitherspoon",
  },
  {
    OwnerFullName: "Chelsea Mulvaney",
    OwnerVerified: false,
    objectID: 24,
    interopID: 24,
    Title: "Journey to the Moon",
    Author: "Crane Sloan",
    Description:
      "Tempor in do consequat adipisicing cillum laborum ipsum aute ut fugiat qui excepteur. Laboris qui commodo eiusmod ad mollit ut sit cupidatat ex ut labore. Est exercitation nisi ut ex. Dolore reprehenderit dolore sint consequat ex excepteur aliqua. Sint voluptate id amet non sunt veniam deserunt ex occaecat pariatur excepteur mollit. Aliqua deserunt reprehenderit Lorem mollit eu ea id sit tempor nisi. Et ex anim amet exercitation fugiat ea mollit.",
    Genre: "Non-Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:43.000Z",
    OwnerID: "chelseamulvaney",
  },
  {
    OwnerFullName: "Chelsea Mulvaney",
    OwnerVerified: false,
    objectID: 84,
    interopID: 84,
    Title: "Once Upon a Breezy Sunday",
    Author: "Norma Thompson",
    Description:
      "Laborum in consectetur mollit Lorem velit aliqua consectetur nisi ad. Voluptate consectetur mollit in reprehenderit ullamco sunt. Id pariatur laboris laborum aute laborum consectetur consequat est pariatur fugiat ea. Do eu irure nostrud labore incididunt mollit duis pariatur est id voluptate deserunt. Mollit culpa esse consequat ipsum irure Lorem. Aliquip irure excepteur exercitation occaecat.",
    Genre: "Other",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:44.000Z",
    OwnerID: "chelseamulvaney",
  },
  {
    OwnerFullName: "Travis Olson",
    OwnerVerified: false,
    objectID: 134,
    interopID: 134,
    Title: "Owls With Pride",
    Author: "Margery Quinn",
    Description:
      "Voluptate officia consequat ad et sit commodo incididunt. Lorem ut consectetur pariatur aute cupidatat laboris est consectetur proident anim eiusmod pariatur laborum. Proident deserunt veniam excepteur nisi elit est qui excepteur eiusmod tempor.",
    Genre: "Mystery",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:45.000Z",
    OwnerID: "travisolson",
  },
  {
    OwnerFullName: "Chelsea Mulvaney",
    OwnerVerified: false,
    objectID: 34,
    interopID: 34,
    Title: "Pilot Of The West",
    Author: "Casey Fox",
    Description:
      "Deserunt nulla sit consectetur exercitation eiusmod aute qui ad et sunt sint. Et mollit et tempor consectetur cupidatat labore ullamco reprehenderit non dolore et. Et minim et adipisicing quis. Exercitation ullamco nostrud anim non sint nulla ipsum dolore proident. Esse duis nulla adipisicing non culpa amet ad laborum eiusmod tempor officia esse consequat. Aliquip adipisicing duis est occaecat occaecat.",
    Genre: "Non-Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:44.000Z",
    OwnerID: "chelseamulvaney",
  },
  {
    OwnerFullName: "Miles Nelson",
    OwnerVerified: false,
    objectID: 214,
    interopID: 214,
    Title: "Power Of My Parents",
    Author: "Francine Garner",
    Description:
      "Et veniam et est ullamco deserunt incididunt sint proident dolor. Deserunt aute cupidatat exercitation ipsum deserunt officia quis commodo cillum sint ullamco qui nisi laboris. Reprehenderit aliqua aute tempor Lorem labore non dolore occaecat do ipsum non et. Lorem aliquip aute nisi consequat.",
    Genre: "Young Adult",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:46.000Z",
    OwnerID: "milesnelson",
  },
  {
    OwnerFullName: "Travis Olson",
    OwnerVerified: false,
    objectID: 114,
    interopID: 114,
    Title: "Rat And Butcher",
    Author: "Garner Burnett",
    Description:
      "Esse eiusmod minim cupidatat occaecat commodo mollit. Culpa enim voluptate sit incididunt. Sunt sint reprehenderit sit nulla veniam magna mollit.",
    Genre: "Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:45.000Z",
    OwnerID: "travisolson",
  },
  {
    OwnerFullName: "Jane Pierson",
    OwnerVerified: false,
    objectID: 294,
    interopID: 294,
    Title: "Revolutionary Road",
    Author: "Odonnell Hicks",
    Description:
      "Ea id commodo occaecat enim ex. Aliqua do eu dolore consectetur quis qui. Reprehenderit ex eiusmod commodo laborum id velit do Lorem ea. Reprehenderit cillum non sit quis ad nostrud voluptate aute cillum quis labore pariatur nostrud.",
    Genre: "Other",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:48.000Z",
    OwnerID: "janereader",
  },
  {
    OwnerFullName: "Miles Nelson",
    OwnerVerified: false,
    objectID: 224,
    interopID: 224,
    Title: "Scourge Of The Stars",
    Author: "Merle Cunningham",
    Description:
      "Tempor enim aliquip commodo non officia consequat esse in. Esse incididunt consectetur duis in cillum sit. Nulla enim cupidatat et occaecat veniam incididunt pariatur commodo Lorem qui exercitation. Mollit velit quis exercitation nostrud ut deserunt dolor exercitation deserunt in fugiat velit. Labore ea nulla magna ut cupidatat est aliqua proident deserunt ex incididunt et laboris. Eiusmod ut id adipisicing eu deserunt eu nisi enim voluptate commodo sunt.",
    Genre: "Other",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:47.000Z",
    OwnerID: "milesnelson",
  },
  {
    OwnerFullName: "Travis Olson",
    OwnerVerified: false,
    objectID: 124,
    interopID: 124,
    Title: "Sister Sister",
    Author: "Monroe Salazar",
    Description:
      "Mollit dolor id voluptate et aliquip irure ipsum in ut commodo ex Lorem amet. Sunt dolor irure dolore id elit minim Lorem aute irure ullamco ut velit aliqua commodo. Do et cillum exercitation dolor sint exercitation labore proident commodo id non velit mollit ipsum.",
    Genre: "Young Adult",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:45.000Z",
    OwnerID: "travisolson",
  },
  {
    OwnerFullName: "Jane Pierson",
    OwnerVerified: false,
    objectID: 254,
    interopID: 254,
    Title: "Soldier With Immortality",
    Author: "Giles Harding",
    Description:
      "Et Lorem laborum aliquip duis non nulla pariatur tempor laboris ut aliqua. Eu cillum magna labore occaecat elit eu excepteur in. Culpa et tempor do enim ex enim culpa nulla. Occaecat laborum minim id ea aliquip deserunt ea dolor non. Voluptate do labore aliquip proident officia cupidatat amet sunt aliqua veniam cillum qui qui. Ad aute id sunt sunt ea qui mollit proident laborum et cupidatat.",
    Genre: "Mystery",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:47.000Z",
    OwnerID: "janereader",
  },
  {
    OwnerFullName: "Chelsea Mulvaney",
    OwnerVerified: false,
    objectID: 94,
    interopID: 94,
    Title: "Sounds In The Shadows",
    Author: "Melton Bray",
    Description:
      "Laborum ullamco excepteur fugiat fugiat occaecat mollit elit cillum officia. Laborum eu officia veniam Lorem in velit. Aliqua nulla esse pariatur et sit mollit.",
    Genre: "Mystery",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:45.000Z",
    OwnerID: "chelseamulvaney",
  },
  {
    OwnerFullName: "DJ Steinmetz",
    OwnerVerified: false,
    objectID: 334,
    interopID: 334,
    Title: "To Kill A Mockingbird",
    Author: "Harper Lee",
    Description:
      "To Kill a Mockingbird is a novel by the American author Harper Lee. It was published in 1960 and, instantly successful in the United States, it is widely read in high schools and middle schools. To Kill a Mockingbird has become a classic of modern American literature, winning the Pulitzer Prize.",
    Genre: "Non-Fiction",
    ImageURL: null,
    created_at: "2021-03-25T06:17:03.000Z",
    OwnerID: "djreader",
  },
  {
    OwnerFullName: "Chelsea Mulvaney",
    OwnerVerified: false,
    objectID: 44,
    interopID: 44,
    Title: "Trinkets Exploit",
    Author: "Good Simmons",
    Description:
      "Id sit anim in quis nisi tempor nisi mollit pariatur nostrud tempor duis veniam sit. Nisi aliquip aliqua Lorem esse. Aliqua anim mollit Lorem sit ea magna. Deserunt ea velit id nisi ex dolor ad excepteur deserunt proident.",
    Genre: "Fiction",
    ImageURL: "http://placehold.it/160x250",
    created_at: "2021-03-25T01:09:44.000Z",
    OwnerID: "chelseamulvaney",
  },
];

index
  .saveObjects(objects)
  .then(({ objectIDs }) => {
    console.log(objectIDs);
  });
